name: SAST & SCA Strict + CSV (Fail)
on:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run SAST (strict CSV)
        uses: docker://fluidattacks/sast:latest
        with:
          args: scan /workspace --config /workspace/fa/sast_config.yml

      - name: Run SCA (strict CSV)
        uses: docker://fluidattacks/sca:latest
        with:
          args: scan /workspace --config /workspace/fa/sca_config.yml
