name: SAST & SCA & OAWSP Strict
 
on:
  workflow_dispatch:
 
jobs:
  sast-scan:
    name: Fluid Attacks SAST
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Run Fluid Attacks SAST
        id: sast_scan
        run: |
          docker run --rm \
            -v "$PWD:/src" \
            fluidattacks/sast:latest \
            sast --strict scan /src/fluidattacks-config.yaml
 
      - name: Upload SAST CSV
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sast-results
          path: |
            Fluid-Attacks-Results-sast.csv
            **/*.csv
 
  sca-scan:
    name: Fluid Attacks SCA
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Run Fluid Attacks SCA
        id: sca_scan
        run: |
          docker run --rm \
            -v "$PWD:/src" \
            fluidattacks/sca:latest \
            sca --strict scan /src/fluidattacks-config.yaml
 
      - name: Upload SCA CSV
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sca-results
          path: |
            Fluid-Attacks-Results-sca.csv
            **/*.csv

  owasp-dependency-check:
    name: OWASP Dependency Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@v3.0.2
        with:
          project: "MiProyecto"
          path: "."
          format: "HTML,JSON"
          out: "dependency-check-report"

      - name: Upload OWASP report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: dependency-check-report